ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "syncedGroupId" TEXT;
ALTER TYPE "TenantAuditAction" ADD VALUE IF NOT EXISTS 'ENTRA_GROUP_REMOVED';
ALTER TYPE "TenantAuditAction" ADD VALUE IF NOT EXISTS 'ENTRA_RECONNECTED';